config/routes.rb
Gaslight::Application.routes.draw do

  github_authenticate(team: :gaslight) do
    ActiveAdmin.routes(self)
  end

  resource :contact, controller: :contact, only: :create

  resources :posts, path: '/blog', except: :show do
    collection do
      get "/:year(/:month(/:day))" => "posts#for_date", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
      get :search
      get :archive
    end

    member do
      get :podcast_iframe
    end
  end

  get 'blog/:slug', to: 'posts#show'
  get 'post/:id(/:slug)', to: 'posts#old' # handle old tumblr urls

  get 'sitemap.xml' => 'sitemaps#index', as: 'sitemap', defaults: { format: "xml" }

  get '/login' => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  # catch all the pages
  get '/:id', to: 'pages#show', as: :static
  get '/home', to: 'pages#show', id: 'home', as: :home

  # redirect to /home. Lets the app rewrite requests
  # and caches the page(s).
  root to: redirect("/home")
end

app/models/post.rb
class Post < ActiveRecord::Base

  def self.published
    where('posts.published_at <= ?', Time.now)
  end

  def self.by_publish_date
    order('posts.published_at desc')
  end

  def self.recent(max = 5)
    published.by_publish_date.limit(max)
  end

  def self.tagged(tag)
    tag ? published.tagged_with(tag.split) : scoped
  end

  def self.search(query)
    published.where('lower(posts.body) like lower(?)', "% #{query} %")
  end

  def self.written_by(author)
    published.where(author: author).by_publish_date
  end

  def self.posted_on(year = nil, month = nil, day = nil)
    posts = published
    posts = posts.where('extract(year  from posts.published_at) = ?', year) unless year.nil?
    posts = posts.where('extract(month from posts.published_at) = ?', month) unless month.nil?
    posts = posts.where('extract(day   from posts.published_at) = ?', day) unless day.nil?
    posts
  end

  def self.authors
    published.select('posts.author, count(posts.id) as post_count').group('posts.author').order('post_count desc')
  end

  def self.podcasts
    tagged_with('podcast')
  end

  def self.articles
    tagged_with('podcast', exclude: true)
  end

  validates_presence_of :title, :body, :author
  validates_length_of :title, maximum: 255

  after_validation :update_html

  acts_as_taggable
  acts_as_url :title, url_attribute: :slug, sync_url: true

  def to_param
    slug
  end

  def published_on
    (published_at || Time.now).to_date
  end

  def title
    read_attribute(:title) || ""
  end

  def next
    Post.where("posts.published_at > ?", published_at).order("posts.published_at asc").first
  end

  def previous
    Post.where("posts.published_at < ?", published_at).order("posts.published_at desc").first
  end

  def type
    return "audio" if audio_url.present?
    "article"
  end

  def related(limit = 10)
    find_related_tags.limit(limit).to_a
  end

  def author_info
    @a ||= Author.find_by_tumblr(self.author)
    @a ||= {}
  end

  def author_name
    author_info[:name]
  end

  def author_email
    author_info[:email]
  end

  def author_google_plus_url
    author_info[:google_plus]
  end

  def published?
    persisted? && published_at && published_at <= Time.now
  end

  private

  def update_html
    return true if body.nil?
    self.html = Renderer.render(body)
  end
end

app/controllers/posts_controller.rb
require 'rewrite'

class PostsController < ApplicationController

  respond_to :html, :rss, :json

  expose(:posts) { Post.published.by_publish_date }
  expose(:post) { Post.published.find_by_slug(params[:slug] || params[:id]) }
  expose(:popular_tags) { Post.tag_counts.order('count desc').limit(20) }
  expose(:authors) { Post.authors }
  expose(:author) { Author.find_by_tumblr(params[:author]) }

  def index
    self.posts = self.posts.written_by([params[:author]]) if params[:author]
    self.posts = self.posts.tagged_with([params[:tagged]]) if params[:tagged]
    self.posts = self.posts.page(params[:page]).per(items_per_page)
    respond_with posts
  end

  def for_date
    self.posts = Post.posted_on(params[:year], params[:month], params[:day])
    @total = Post.published.count
    respond_with self.posts
  end

  def archive
    self.posts = posts.group_by { |post| post.published_at.beginning_of_month }
    @total = Post.published.count
    respond_with self.posts
  end

  def search
    self.posts = Post.search(params[:q])
    respond_with posts, template: 'posts/index'
  end

  def old
    new_host = Rails.env.development? ? 'gaslight.dev' : 'gaslight.co'
    new_slug = Rewrite.new_post_url(request.fullpath)
    new_url = new_slug ? post_url(new_slug, host: new_host) : posts_url(host: new_host)
    redirect_to new_url, status: 301
  end

  def podcast_iframe
    respond_with post, layout: false
  end

  protected

  def search_date
    year = (params[:year] || Date.today.year).to_i
    month = (params[:month] || Date.today.month).to_i
    day = (params[:day] || Date.today.day).to_i
    Date.new(year, month, day)
  end
  helper_method :search_date

  def items_per_page
    return 15 if request.format == 'rss'
    index? ? 3 : 100
  end

  def index?
    actions = %w(q tagged author year)
    (params.keys & actions).none?
  end
end

app/views/posts/_admin.html.haml
- if github_user
  %h3 Admin
  %ul
    %li= link_to('Admin', admin_root_path)
    %li= link_to('Edit this Post', [:edit, :admin, post]) if post

app/views/posts/_form.html.erb
<%= semantic_form_for [:admin, @post] do |f| %>
  <%= f.inputs do %>
    <%= f.input :author, as: :select, collection: Author.all %>
    <%= f.input :title %>
    <%= f.input :body, as: :hidden %>
    <li class="text input required">
      <label class="label">Body<abbr class="required">*</abbr></label>
        <div id="editor"></div>
      </label>
    </li>
    <%= f.input :description, label: 'Description (TL;DR)', hint: 'A paragraph, maybe. This shows up when links are shared and on search engines.' %>
    <%= f.input :audio_url, label: 'Audio File URL', hint: 'Only useful for Podcasts.' %>
    <%= f.input :slug, hint: 'This is automatically created based on your title, but you can override it here.' %>
    <%= f.input :tag_list, hint: 'Comma separated. Ex: "cincinnati, javascript"' %>
    <%= f.input :published_at, as: :datetime_picker, hint: 'You can set this to a future date, too! Anything prior to now is "published".' %>
  <% end %>
  <%= f.actions do %>
    <%= f.action :submit %>
  <% end %>
<% end %>

app/views/posts/_index_sidebar.html.haml
.columns.three.prepend-1.sidebar
  = render partial: 'search_form'
  = link_to_unless_current('Recent Posts', posts_path)
  |
  = link_to_unless_current('Archive', archive_posts_path)
  %h3.sidebar__heading Tags
  .tag-container
    = popular_tag_links(popular_tags)
  %h3.sidebar__heading Authors
  %ul
    - authors.each do |post|
      %li
        = link_to(post.author_name || "Other", posts_path(author: post.author))
        (#{pluralize(post.post_count, 'post')})

app/views/posts/_meta.html.haml
- content_for :head do
  %meta{property: "og:site_title", content: "Gaslight Blog"}
  %meta{property: "og:site_name", content: "Gaslight Blog"}
  %meta{property: "og:image", content: "http://gaslight.co#{image_path('home/logo.png')}"}
  %link{rel: 'publisher', href: 'https://plus.google.com/b/108634148069175104559/108634148069175104559'}

  %meta{property: "author", content: post.author}
  %meta{property: "og:type", content: "article"}
  %meta{property: "og:title", content: post.title}
  %meta{property: "og:article:published_time", content: post.published_at.iso8601}
  %meta{property: "og:url", content: post_url(post)}

  - post.tags.each do |tag|
    %meta{property: "og:article:tag", content: tag}

  - if post.audio_url.present?
    %meta{property: "og:audio", content: post.audio_url}
    %meta{property: "og:audio:type", content: "audio/mp3"}

  - if post.description
    %meta{property: "og:description", content: "#{post.description}"}

  - if post.author_google_plus_url.present?
    %link{rel: 'author', href: post.author_google_plus_url}

app/views/posts/_player.html.haml
- if post.audio_url.present?
  .post__player
    %audio{itemprop: 'audio', src: post.audio_url}

app/views/posts/_post.html.haml
%article.post{itemscope: true, itemtype: 'http://schema.org/BlogPosting'}
  %header.post__header.instapaper_title
    %h2.post__title
      = link_to(post_url(post), itemprop: 'url') do
        %span{itemprop: 'name headline'}= post.title
      = image_tag(gravatar_url(post.author_email, '70x70'), class: 'post__avatar')
    %span.post__author{itemtype: 'http://schema.org/Person', itemscope: true}
      by
      = link_to(post.author_name, posts_path(author: post.author), rel: "author", itemprop: 'name')
      %meta{itemprop: 'image', content: gravatar_url(post.author_email, '70x70')}
    %time.post__time{pubdate: true, datetime: post.published_at.iso8601, itemprop: 'datePublished'}
      = link_to(l(post.published_on, format: :nice), post)
  %section.post__body.instapaper_body{itemprop: 'articleBody'}
    = render(partial: 'posts/player', locals: { post: post })
    = raw(post.html)

app/views/posts/_post_list.html.haml
%ul.post__list
  - posts.each do |post|
    %li= link_to(post.title, post)

app/views/posts/_search_form.html.haml
= form_tag(search_posts_path, method: :get) do
  = text_field_tag :q, params[:q], placeholder: 'Search...', class: 'search-bar'

app/views/posts/_show_sidebar.html.haml
.columns.three.prepend-1.sidebar
  = render partial: 'search_form'
  %h3.sidebar__heading Tags
  .tag-container
    = popular_tag_links(post.tag_counts)
  %h3.sidebar__heading More
  - if post.previous
    %p.sidebar__nav Previous: #{link_to(post.previous.title, post.previous)}
  - if post.next
    %p.sidebar__nav Next: #{link_to(post.next.title, post.next)}
  - if post.related.any?
    %h3.sidebar__heading More Like This
    %ul
      - post.related.each do |post|
        %li.related-post__list= link_to(post.title, post)

app/views/posts/_tweet.html.haml
<a href="https://twitter.com/share" class="twitter-share-button" data-via="teamgaslight" data-dnt="true">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>

app/views/posts/archive.html.haml
- content_for(:title) { "Gaslight Blog: Archive" }

= render partial: 'application/nav'
#main.container.row
  .columns.eight
    - posts.each do |month, posts|
      %h3
        = l(month.to_date, format: :year_and_month)
        %span
          (#{pluralize(posts.count, 'post')})
      = render partial: 'post_list', locals: { posts: posts }
  = render partial: 'index_sidebar'
= render partial: 'application/footer'

app/views/posts/for_date.html.haml
- content_for(:title) { "Gaslight Blog: Archive " }
= render partial: 'application/nav'
#main.container.row
  .columns.eight
    %h1
      #{pluralize(posts.count, 'post')} written
      - if params[:day].present?
        on
        = l(search_date, format: :nice)
      - elsif params[:month].present?
        in
        = l(search_date, format: :year_and_month)
      - else
        in
        = l(search_date, format: :year)
    = render partial: 'post_list', locals: { posts: posts }
  = render partial: 'index_sidebar'
= render partial: 'application/footer'

app/views/posts/podcast_iframe.html.haml
!!!5
%html
  %head
    %meta{name: "robots", content: "noindex,nofollow"}
    = javascript_include_tag 'application'
    = stylesheet_link_tag 'application'
  %body
    = render partial: 'player'
    :javascript
      $('audio').mediaelementplayer({
        pluginPath: '/assets/',
        audioWidth: '100%'
      });

app/views/posts/show.html.haml
- content_for(:title) { post.title }
= render(partial: 'meta')

= render partial: 'application/nav'
#main.container.row
  .columns.eight
    = render post
    .comments#disqus_thread
    %noscript
      Please enable JavaScript to view the
      %a{href: "http://disqus.com/?ref_noscript"} comments powered by Disqus
  = render partial: 'posts/show_sidebar'

= render partial: 'application/footer'

- content_for(:javascript) do
  :javascript

    $(window).load(function(){
      shareView = new Gaslight.Views.ShareView({
        shareUrl: window.location,
        targetEl: $('.post'),
        viewportEl: $(window)
      });
      $('body').append(shareView.render().el)

      var disqus_shortname = '#{ENV.fetch('DISQUS_SHORTNAME')}';
      (function() {
          var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
          dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
          (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
      })();
    });