config/routes.rb
Gaslight::Application.routes.draw do

  github_authenticate(team: :gaslight) do
    ActiveAdmin.routes(self)
  end

  resource :contact, controller: :contact, only: :create

  resources :posts, path: '/blog', except: :show do
    collection do
      get "/:year(/:month(/:day))" => "posts#for_date", constraints: { year: /\d{4}/, month: /\d{2}/, day: /\d{2}/ }
      get :search
      get :archive
    end

    member do
      get :podcast_iframe
    end
  end

  get 'blog/:slug', to: 'posts#show'
  get 'post/:id(/:slug)', to: 'posts#old' # handle old tumblr urls

  get 'sitemap.xml' => 'sitemaps#index', as: 'sitemap', defaults: { format: "xml" }

  get '/login' => 'sessions#create', as: :login
  get '/logout' => 'sessions#destroy', as: :logout

  # catch all the pages
  get '/:id', to: 'pages#show', as: :static
  get '/home', to: 'pages#show', id: 'home', as: :home

  # redirect to /home. Lets the app rewrite requests
  # and caches the page(s).
  root to: redirect("/home")
end

app/views/layouts/_logo.html.erb
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 1024 768" enable-background="new 0 0 1024 768" xml:space="preserve">
<g>
	<g>
		<g>
			<g>
				<path d="M323.682,548.093c-4.519,4.596-9.937,6.651-16.506,6.651c-6.244,0-11.502-2.136-15.77-6.407
					c-2.549-2.544-4.108-5.502-4.763-8.787c-0.657-3.284-0.986-8.129-0.986-14.536c0-6.409,0.329-11.252,0.986-14.536
					c0.654-3.366,2.214-6.242,4.763-8.787c4.268-4.269,9.525-6.407,15.77-6.407c13.304,0,20.448,8.543,22.011,18.726h-11.503
					c-1.394-5.667-4.843-8.542-10.508-8.542c-3.044,0-5.502,1.07-7.309,3.124c-2.138,2.707-2.794,4.843-2.794,16.423
					c0,11.496,0.491,13.794,2.794,16.508c1.722,2.053,4.187,3.038,7.309,3.038c3.365,0,6.074-1.069,8.125-3.287
					c1.725-1.967,2.634-4.594,2.634-7.801v-2.218h-10.759v-9.524h22.086v8.54C329.262,538.808,327.706,543.819,323.682,548.093z"/>
				<path d="M378.401,554.251l-3.449-10.348h-20.776l-3.534,10.348h-11.904l21.27-58.474h8.949l21.353,58.474H378.401z
					 M364.768,513.022l-7.388,21.27h14.532L364.768,513.022z"/>
				<path d="M419.651,554.744c-8.865,0-15.603-1.887-21.352-7.721l7.391-7.391c3.698,3.697,8.703,4.927,14.123,4.927
					c6.736,0,10.348-2.547,10.348-7.226c0-2.055-0.571-3.777-1.805-4.929c-1.146-1.066-2.465-1.643-5.176-2.054l-7.061-0.984
					c-5.009-0.74-8.705-2.3-11.332-4.847c-2.795-2.791-4.188-6.569-4.188-11.498c0-10.428,7.72-17.739,20.365-17.739
					c8.05,0,13.883,1.969,18.892,6.816l-7.229,7.146c-3.696-3.531-8.13-4.022-11.994-4.022c-6.074,0-9.031,3.367-9.031,7.388
					c0,1.479,0.493,3.04,1.727,4.188c1.148,1.069,3.04,1.974,5.42,2.303l6.898,0.982c5.338,0.739,8.707,2.22,11.172,4.518
					c3.117,2.958,4.516,7.228,4.516,12.403C441.335,548.337,431.89,554.744,419.651,554.744z"/>
				<path d="M457.014,554.251v-58.474h11.416v48.291h26.53v10.183H457.014z"/>
				<path d="M509.158,554.251v-58.474h11.416v58.474H509.158z"/>
				<path d="M575.187,548.093c-4.519,4.596-9.941,6.651-16.508,6.651c-6.242,0-11.501-2.136-15.77-6.407
					c-2.547-2.544-4.107-5.502-4.768-8.787c-0.648-3.284-0.984-8.129-0.984-14.536c0-6.409,0.336-11.252,0.984-14.536
					c0.66-3.366,2.221-6.242,4.768-8.787c4.269-4.269,9.527-6.407,15.77-6.407c13.303,0,20.445,8.543,22.01,18.726h-11.496
					c-1.4-5.667-4.847-8.542-10.514-8.542c-3.04,0-5.503,1.07-7.31,3.124c-2.138,2.707-2.791,4.843-2.791,16.423
					c0,11.496,0.491,13.794,2.791,16.508c1.725,2.053,4.189,3.038,7.31,3.038c3.364,0,6.078-1.069,8.129-3.287
					c1.727-1.967,2.627-4.594,2.627-7.801v-2.218h-10.756v-9.524h22.092v8.54C580.771,538.808,579.208,543.819,575.187,548.093z"/>
				<path d="M627.575,554.251v-24.477h-19.794v24.477h-11.414v-58.474h11.414v23.9h19.794v-23.9h11.416v58.474H627.575z"/>
				<path d="M679.887,505.96v48.291h-11.416V505.96h-15.276v-10.183h41.967v10.183H679.887z"/>
			</g>
		</g>
		<g>
			<polygon fill="#DD3E31" points="465.938,386.459 440.874,361.397 465.938,336.344 491.002,361.397"/>
			<polygon fill="#F2D719" points="490.924,411.45 465.863,386.381 490.924,361.326 515.993,386.381"/>
			<polygon fill="#62BDE5" points="515.993,386.389 490.924,361.326 515.993,336.268 541.057,361.326"/>
			<path d="M491.002,129.7L286.588,334.114l78.995,0.039L491.002,459.57l125.499-125.495l78.902,0.039L491.002,129.7z
				 M440.896,361.424l50.229-50.22l50.097,50.087l-50.22,50.222L440.896,361.424z M556.735,345.758l-65.61-65.617l-0.64,0.628
				l-65.102,65.121l-38.293-38.288l103.911-103.915L594.9,307.602L556.735,345.758z"/>
		</g>
	</g>
	<g>
		<defs>
				<rect id="SVGID_7_" x="455.578" y="325.902" transform="matrix(0.7071 0.7071 -0.7071 0.7071 399.3413 -241.3651)" width="70.845" height="70.846"/>
		</defs>
		<clipPath id="SVGID_2_">
			<use xlink:href="#SVGID_7_"  overflow="visible"/>
		</clipPath>
		<radialGradient id="SVGID_3_" cx="491.002" cy="361.3242" r="84.1973" gradientUnits="userSpaceOnUse">
			<stop  offset="0.271" style="stop-color:#FFFFFF"/>
			<stop  offset="0.3672" style="stop-color:#F9F9F9"/>
			<stop  offset="0.4975" style="stop-color:#E8E8E8"/>
			<stop  offset="0.6475" style="stop-color:#CBCBCC"/>
			<stop  offset="0.8122" style="stop-color:#A3A4A6"/>
			<stop  offset="0.987" style="stop-color:#717275"/>
			<stop  offset="1" style="stop-color:#6D6E71"/>
		</radialGradient>
		<path clip-path="url(#SVGID_2_)" fill="url(#SVGID_3_)" d="M575.199,361.324c0,46.502-37.697,84.197-84.197,84.197
			c-46.504,0-84.197-37.695-84.197-84.197s37.693-84.197,84.197-84.197C537.502,277.127,575.199,314.822,575.199,361.324z"/>
	</g>
</g>
</svg>

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 9] <html class="crappy-browser" lang="en">
<!--[if gt IE 8]><!-->
%html{lang: 'en', xmlns: "http://www.w3.org/1999/xhtml", 'xmlns:og' => "http://ogp.me/ns#", 'xmlns:fb' => "http://www.facebook.com/2008/fbml"}
  <!--<![endif]-->
  %head
    /[if lt IE 9]
      = javascript_include_tag "html5shiv"
    %title= content_for?(:title) ? content_for(:title) : "Gaslight: Ruby on Rails, iOS and JavaScript development"
    %meta{charset: "utf-8"}/
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no", name: "viewport"}/
    = auto_discovery_link_tag(:rss, posts_url(format: :rss))
    = favicon_link_tag "32x32icon.png"
    = stylesheet_link_tag "application"
    = yield :head
    = csrf_meta_tags
  %body{class: "#{controller.controller_name} #{controller.action_name}"}
    = yield
    = javascript_include_tag "application"
    = yield :javascript